expirience/main/routes.py
"""
Runns main and routes
"""
from flask import Blueprint, request
from flask import render_template
from ..data_base import Projects

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    """
    renders home page
    """
    page = request.args.get('page', 1, type=int)
    jobs = Projects.query.paginate(page=page, per_page=5)
    return render_template('home.html', title="Home", jobs=jobs)


@main.route('/about')
def about():
    """
    renders about page
    """
    return render_template('about.html', title="About")

expirience/projects/routes.py
"""
Project routes or Jobs
"""
from flask import Blueprint, render_template, request, redirect, url_for, flash
from ..data_base import Projects, User
from .utils import send_to_job_taker, send_to_job_poster
from .. import db
from flask_login import current_user, login_required
from .forms import CreateJobForm

jobs = Blueprint('jobs', __name__)


@jobs.route('/projects')
def projects():
    """
    route to all projects page
    """
    render_template('projects.html', title="Projects")


@jobs.route('/user/<string:username>', methods=['GET', 'POST'])
def user_jobs(username):
    """
    gets user specific jobs
    """
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    jobs = Projects.query.filter_by(author=user)\
        .paginate(page=page, per_page=5)
    return render_template('user_jobs.html',
                           title="Home", jobs=jobs, user=user)

@jobs.route('/myprojects', methods=['GET', 'POST'])
@login_required
def myprojects():
    """
    route to user projects page that can be edited
    """
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    if request.method == 'POST':
        project_id = request.form.get('item_id')
        project = Projects.query.get(project_id)
        db.session.delete(project)
        db.session.commit()
        flash('Project deleted!', 'success')
        return redirect(url_for('users.myprojects'))
    projects_current_user = [Projects.query.all(), current_user]
    return render_template('myprojects.html', title="My Projects", form=projects_current_user)

@jobs.route('/createproject', methods=['GET', 'POST'])
@login_required
def createproject():
    """
    route to create project page
    """
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = CreateJobForm()
    if form.validate_on_submit():

        project = Projects(project_name=form.job_title.data,
                           project_description=form.job_description.data,
                           project_link=form.job_link.data,
                           skills_required=form.skills_required.data,
                           author=current_user)
        db.session.add(project)
        db.session.commit()
        flash(f'Project created for {form.job_title.data}!', 'success')
        return redirect(url_for('main.home'))
    return render_template('createproject.html', title="Create Project", form=form)

@jobs.route('/jobs', methods=['GET', 'POST'])
@login_required
def get_job():
    """
    route to get job page and jobsly for job
    """
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    if request.method == 'POST':
        project_id = request.form.get('item_id')
        #project = Projects.query.get(project_id)
        send_to_job_taker(current_user.id, project_id)
        send_to_job_poster(current_user.id, project_id)
        flash('Accepted Job - Email sent', 'success')
        return redirect(url_for('main.home'))
    
    page = request.args.get('page', 1, type=int)
    projects_current_user = [Projects.query.paginate(page=page, per_page=5), current_user]
    return render_template('jobs.html', title="Get Job", form=projects_current_user)

expirience/skills/routes.py
"""
routes for the skills pages
"""
from flask import render_template, redirect, url_for, flash
from flask_login import current_user, login_required
from ..data_base import Skills, db
from .forms import SkillsForm
from flask import Blueprint

skills = Blueprint('skills', __name__)


@skills.route('/addskills', methods=['GET', 'POST'])
@login_required
def addskills():
    """
    renders add skills page
    """
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = SkillsForm()
    if form.validate_on_submit():
        for val, ky in form.data.items():
            if ky == "skill":
                skill = Skills(skill=val, author=current_user)
                db.session.add(skill)
                db.session.commit()
            elif ky == "skill_1":
                skill = Skills(skill_1=val, author=current_user)
                db.session.add(skill)
                db.session.commit()
            elif ky == "skill_2":
                skill = Skills(skill_2=val, author=current_user)
                db.session.add(skill)
                db.session.commit()
            elif ky == "skill_3":
                skill = Skills(skill_3=val, author=current_user)
                db.session.add(skill)
                db.session.commit()
            elif ky == "skill_4":
                skill = Skills(skill_4=val, author=current_user)
                db.session.add(skill)
                db.session.commit()
        flash('Skills added!', 'success')
        return redirect(url_for('main.home'))
    return render_template('addskills.html', title="Add Skills", form=form)

expirience/users/routes.py
"""
User funtionality rooutes
"""
from mailersend import emails
from .forms import (RegisterForm, ResetPasswordForm, RequestResetForm,
                          LoginForm, UserUpdateForm)
from flask_login import login_user, current_user, logout_user, login_required

from .. import db, bcrypt
from ..data_base import User, Projects, Skills
from .utils import save_picture, send_reset_email


key = open("expirience/access_token.txt", "r").read().rstrip("\n")

mailer = emails.NewEmail(key)

user_id = None

from flask import Blueprint, render_template, redirect, url_for, flash, request


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """
    renders register page
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data,
                    country=form.country.data,
                    git_hub=form.git_hub.data,
                    password=hashed_password,
                    image_file='Generic-Profile-Image.png')
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title="Register", form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    """
    renders login page and hadles validation
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            flash('Login Successful', 'success')
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title="Login" , form=form)


@users.route('/logout')
def logout():
    """
    logs out user
    """
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/editprofile', methods=['GET', 'POST'])
@login_required
def editprofile():
    """
    renders edit profile page
    """
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    form = UserUpdateForm()
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.country = form.country.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.profile'))
    return render_template('editprofile.html', image_file=image_file,
                           title="Edit Profile", form=form)

@users.route('/myprojects', methods=['GET', 'POST'])
@login_required
def myprojects():
    """
    route to user projects page that can be edited
    """
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    
    if request.method == 'POST':
        project_id = request.form.get('item_id')
        project = Projects.query.get(project_id)
        db.session.delete(project)
        db.session.commit()
        flash('Project deleted!', 'success')
        return redirect(url_for('users.myprojects'))
    projects_current_user = [Projects.query.all(), current_user]
    return render_template('myprojects.html', title="My Projects", form=projects_current_user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    """
    resets password
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    """
    Takes in reset token
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

@users.route('/user/<string:username>', methods=['GET', 'POST'])
def user_jobs(username):
    """
    gets user specific jobs
    """
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    jobs = Projects.query.filter_by(author=user)\
        .paginate(page=page, per_page=5)
    return render_template('user_jobs.html',
                           title="Home", jobs=jobs, user=user)

@users.route('/profile')
@login_required
def profile():
    """
    renders profile page
    """
    if not current_user.is_authenticated:
        return redirect(url_for('home'))
    image_file = image_file = url_for('static',
                                      filename='profile_pics/' + \
                                        current_user.image_file)
    if not Skills.query.all():
        return render_template('profile.html', title="Profile", form=None)
    return render_template('profile.html', title="Profile", image_file=image_file,
                           form=Skills.query.filter_by(author=current_user).all())

expirience/templates/about.html
{% extends "layout.html" %}
{% block content %}

<div class="container">
    
    </style>
    <h1>About ALXpirience</h1>
    <p>Welcome to <strong>ALXpirience</strong>, the premier platform connecting software engineering students across Africa. Our mission is to foster collaboration, skill-sharing, and career growth within the African tech community. Whether you're a student, a job seeker, or a project creator, ALXpirience provides the tools you need to thrive.</p>
    <h2>Features</h2>
    <ul>
        <li><strong>User Authentication:</strong> Securely register and log in with your email address, username, and password. Choose your country during registration to connect with peers from your region.</li>
        <li><strong>User Profiles:</strong> Create a detailed profile showcasing your skills, interests, and background. Let others know what you're passionate about and what you're looking for in your tech journey.</li>
        <li><strong>Job Board:</strong> Post job opportunities or project collaborations. Specify requirements, duration, and compensation. Browse job listings created by other students and express interest.</li>
        <li><strong>Collaboration Opportunities:</strong> Hire fellow students for your projects. Need a coding partner? Find one on ALXpirience. Showcase your skills and contribute to exciting projects.</li>
        <li><strong>Job Search:</strong> Explore job listings posted by other students. Filter by skills, location, or project type. Apply directly through the platform.</li>
    </ul>
    <h2>Our Vision</h2>
    <p>ALXpirience aims to bridge the gap between African software engineers and the global tech industry. We believe that collaboration, mentorship, and networking are essential for success. Join us on this journey to unlock your potential and make an impact!</p>
    <h2>Get Involved</h2>
    <ol>
    <li>Create Your Profile: Set up your ALXpirience profile today. Let the community know who you are and what you're passionate about.</li>
    <li>Post Jobs or Projects: Have a project idea? Need help with a task? Post it on our job board and find the right collaborators.</li>
        <li>Explore Opportunities: Browse job listings, connect with other students, and take your tech career to new heights.</li>
    </ol>
    <h2>Contact Us</h2>
    <p>Have questions or feedback? Reach out to our team at <a href="mailto:contact@alxpirience.com">contact@alxpirience.com</a>.</p>
    <p>Let's build a stronger African tech community together!</p>
</div>
{% endblock %}

expirience/templates/createproject.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Project</legend>
            <div class="form-group">
                {{ form.job_title.label(class="form-control-label") }}
                {{ form.job_title(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.job_description.label(class="form-control-label") }}
                {{ form.job_description(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.job_link.label(class="form-control-label") }}
                {{ form.job_link(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.skills_required.label(class="form-control-label") }}
                {{ form.skills_required(class="form-control form-control-lg") }}
            </div>
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
{% endblock %}

expirience/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <title>Home Page</title>
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
          <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">
              <img src="static/images/large.ico" alt="" width="30" height="24" class="d-inline-block align-text-top">
            </a>
            <a class="navbar-brand mr-4" href="/">ALXpirience</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="/about">About</a>
              </div>
              <!-- Loggedin vs not loggedd in -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    User: {{ current_user.username }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('users.editprofile') }}">Edit Profile</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('users.profile') }}">View Profile</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('skills.addskills') }}">Add Skills</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('jobs.createproject') }}">Create Job</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('jobs.myprojects') }}">View/Delete My Jobs</a></li>
                  </ul>
                    <a class="nav-item nav-link" href="{{ url_for('jobs.get_job') }}">Jobs</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
      <h1>Jobs</h1>
      {% for job in jobs %}
        <article class="media content-section">
          <div class="media-body">
            <h2 class="article-title" href="#">{{ job.project_name }}</h2>
            <p class="article-content">{{ job.project_description }}</p>
            <h6 href="#">Skills needed: {{ job.skills_required }}</h6>
            <h6><a href="https://{{ job.project_link }}" target="_blank">{{ job.project_link }}</a></h6>
          </div>
        </article>
      {% endfor %}
      {% for page_num in jobs.iter_pages(left_edge=1, right_edge=1, right_current=2) %}
        {% if page_num %}
          {% if jobs.page == page_num %}
            <a class="btn btn-secondary mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          
        {% endif %}
      {% endfor %}
    </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

expirience/templates/jobs.html
{% extends "layout.html" %}
{% block content %}
{% for project in form[0] %}
    {% if project.author.id != form[1].id %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ project.project_name }}</h5>
                <p class="card-text">{{ project.project_description }}</p>
                <a href="project.project_link" class="card-link">{{ project.project_link }}</a>

                <form action="{{ url_for('jobs.get_job') }}" method="post">
                    <input type="hidden" name="item_id" value="{{ project.id }}">
                    <button type="submit" class="btn btn-sm btn-primary m-1" >Accept Job</button>
                </form>
            </div>
        </div>
    {% else %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ project.project_name }}</h5>
                <p class="card-text">{{ project.project_description }}</p>
                <a href="project.project_link" target="_blank" class="card-link">{{ project.project_link }}</a><br>
                <button type="button" class="btn btn-sm btn-primary m-1" disabled>My Project</button>
            </div>
        </div></br>
    {% endif %}
{% endfor %}
{% for page_num in form[0].iter_pages(left_edge=1, right_edge=1, right_current=2) %}
        {% if page_num %}
          {% if form[0].page == page_num %}
            <a class="btn btn-secondary mb-4" href="{{ url_for('jobs.get_job', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-info mb-4" href="{{ url_for('jobs.get_job', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          
        {% endif %}
      {% endfor %}
{% endblock %}

expirience/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <title>Home Page</title>
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
          <div class="container-fluid">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">
              <img src="static/images/large.ico" alt="" width="30" height="24" class="d-inline-block align-text-top">
            </a>
            <a class="navbar-brand mr-4" href="/">ALXpirience</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                <a class="nav-item nav-link" href="/about">About</a>
              </div>
              <!-- Loggedin vs not loggedd in -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    User: {{ current_user.username }}
                  </a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{{ url_for('users.editprofile') }}">Edit Profile</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('users.profile') }}">View Profile</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('skills.addskills') }}">Add Skills</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('jobs.createproject') }}">Create Job</a></li>
                    <li><a class="dropdown-item" href="{{ url_for('jobs.myprojects') }}">View/Delete My Jobs</a></li>
                  </ul>
                    <a class="nav-item nav-link" href="{{ url_for('jobs.get_job') }}">Jobs</a>
                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

expirience/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-conntrol-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-conntrol-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-conntrol-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-conntrol-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-3">
                <a href="{{ url_for('users.reset_request') }}">Forgot Your Password?</a>
            </small>
        </form>
    </div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Register Now!</a>
        </small>
    </div>
                
{% endblock %}

expirience/templates/myprojects.html
{% extends "layout.html" %}
{% block content %}
{% for project in form[0] %}
    {% if project.author.id == form[1].id %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ project.project_name }}</h5>
                <p class="card-text">{{ project.project_description }}</p>
                <a href="project.project_link" class="card-link">{{ project.project_link }}</a>
                
                <form action="{{ url_for('jobs.myprojects') }}" method="post">
                    <input type="hidden" name="item_id" value="{{ project.id }}">
                    <button type="submit" class="btn btn-sm btn-primary m-1" >Delete</button>
                </form>
            </div>
        </div>
    {% else %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ project.project_name }}</h5>
                <p class="card-text">{{ project.project_description }}</p>
                <a href="project.project_link" class="card-link">{{ project.project_link }}</a><br>
                <button type="button" class="btn btn-sm btn-primary m-1" disabled>Accept  Job</button>
            </div>
        </div>
    {% endif %}
{% endfor %}
{% endblock %}

expirience/templates/user_jobs.html
{% extends "layout.html" %}
{% block content %}
<h1 class="mb-3">Projects by {{ user.username }} ({{ jobs.total }})  </h1>
{% for project in jobs %}
    {% if project.author == user %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ project.project_name }}</h5>
                <p class="card-text">{{ project.project_description }}</p>
                <a href="project.project_link" class="card-link">{{ project.project_link }}</a>
                <form action="{{ url_for('jobs.get_job') }}" method="post">
                    <input type="hidden" name="item_id" value="{{ project.id }}">
                    <button type="submit" class="btn btn-sm btn-primary m-1" >Accept Job</button>
                </form>
            </div>
        </div>
    {% endif %}
{% endfor %}
{% for page_num in jobs.iter_pages(left_edge=1, right_edge=1, right_current=2) %}
        {% if page_num %}
          {% if jobs.page == page_num %}
            <a class="btn btn-secondary mb-4" href="{{ url_for('jobs.get_job', page=page_num) }}">{{ page_num }}</a>
          {% else %}
            <a class="btn btn-info mb-4" href="{{ url_for('jobs.get_job', page=page_num) }}">{{ page_num }}</a>
          {% endif %}
        {% else %}
          
        {% endif %}
      {% endfor %}
{% endblock %}